@HostAddress = https://localhost:7335

GET {{HostAddress}}/
Accept: application/json

###

POST {{HostAddress}}/matches
Content-Type: application/json

{
  "winnerId": "player-1",
  "loserId": "player-2",
  "venueName": "arena-1"
}

###

GET {{HostAddress}}/matches?venueName=arena-1
Accept: application/json

###

GET {{HostAddress}}/matches
Accept: application/json

###
